name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chmod op
      run: sudo chmod +x ./configure
    - name: configure
      run: ./configure
    - name: make
      # run: make hello_world.c
      run: gcc -o hello hello_world.c
    - name: run hello output
      run: ./hello
    # - name: make check
    #  run: make check
    # - name: make distcheck
    #  run: make distcheck
